import { ScrollView, View, Text, StyleSheet, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { ArrowLeft, HeartHandshake } from 'lucide-react-native';
import { Brand, Card } from '../src/components/UI';
import { useTheme } from '../src/context/ThemeContext';
const devs=['San Miguel, San Miguel','Hallig, Jommel','Santander, Aliyah','Tapan, Ma. Dhiane','Ordinario, Ira Mae'];
export default function About(){const {theme}=useTheme();return <SafeAreaView style={[s.safe,{backgroundColor:theme.bg}]}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.back()} style={[s.back,{backgroundColor:theme.surface,borderColor:theme.line}]}><ArrowLeft color={theme.text} size={19}/></Pressable><Brand/></View><View style={[s.hero,{backgroundColor:theme.surface2}]}><HeartHandshake color={theme.primary} size={30}/><Text style={[s.title,{color:theme.text}]}>About EqualLearn</Text><Text style={[s.body,{color:theme.muted}]}>A mobile learning application for gender equality education and awareness for Pateros Technological College.</Text></View><Text style={[s.section,{color:theme.text}]}>Developers</Text>{devs.map(n=><Card key={n} style={s.dev}><View style={[s.avatar,{backgroundColor:theme.soft}]}><Text style={{color:theme.primary,fontWeight:'900'}}>{n.slice(0,2).toUpperCase()}</Text></View><Text style={[s.devName,{color:theme.text}]}>{n}</Text></Card>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},content:{padding:18,paddingBottom:34},top:{flexDirection:'row',alignItems:'center',gap:12,marginTop:5,marginBottom:22},back:{width:42,height:42,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},hero:{borderRadius:24,padding:22},title:{fontSize:24,fontWeight:'900',marginTop:12},body:{fontSize:11,lineHeight:18,marginTop:7},section:{fontSize:14,fontWeight:'900',marginVertical:16},dev:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},avatar:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},devName:{fontSize:11,fontWeight:'800'}});
