import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Eye, EyeOff } from 'lucide-react-native';
import { Brand } from '../src/components/UI';
import { useTheme } from '../src/context/ThemeContext';
import { useAuth } from '../src/context/AuthContext';

function goForRole(role){const r=(role||'').toLowerCase();router.replace(r==='student'?'/student/home':r==='teacher'?'/teacher/home':r==='admin'?'/admin/home':'/login');}
export default function Login(){
  const {theme}=useTheme(),{login}=useAuth();
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(){if(!email||!password){setError('Enter your email and password.');return;}setBusy(true);setError('');try{const p=await login(email,password);goForRole(p.role);}catch(e){setError(e.message||'Unable to sign in.');}finally{setBusy(false);}}
  return <SafeAreaView style={[s.safe,{backgroundColor:theme.bg}]}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.wrap}><Brand/><View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.kicker,{color:theme.primary}]}>WELCOME BACK</Text><Text style={[s.title,{color:theme.text}]}>Sign in to EqualLearn</Text><Text style={[s.sub,{color:theme.muted}]}>Student, Teacher, and Admin use the same Firebase login.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={theme.muted} style={[s.input,{color:theme.text,backgroundColor:theme.bg,borderColor:theme.line}]}/><View style={[s.passwordWrap,{backgroundColor:theme.bg,borderColor:theme.line}]}><TextInput value={password} onChangeText={setPassword} secureTextEntry={!showPassword} placeholder="Password" placeholderTextColor={theme.muted} style={[s.passwordInput,{color:theme.text}]}/><Pressable onPress={()=>setShowPassword(v=>!v)} style={s.eyeButton}>{showPassword?<EyeOff color={theme.muted} size={18}/>:<Eye color={theme.muted} size={18}/>}</Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={submit} style={[s.button,{backgroundColor:theme.primary,opacity:busy?.7:1}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Sign in</Text>}</Pressable><View style={s.links}><Pressable onPress={()=>router.push('/forgot-password')}><Text style={[s.link,{color:theme.primary}]}>Forgot password?</Text></Pressable><Pressable onPress={()=>router.push('/register')}><Text style={[s.link,{color:theme.primary}]}>Create student account</Text></Pressable></View></View></View></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},flex:{flex:1},wrap:{flex:1,justifyContent:'center',padding:22,gap:25},card:{borderWidth:1,borderRadius:24,padding:22},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{fontSize:27,fontWeight:'900',marginTop:8},sub:{fontSize:11,marginTop:6,marginBottom:18,lineHeight:17},input:{height:50,borderWidth:1,borderRadius:14,paddingHorizontal:14,marginBottom:10,fontSize:13},passwordWrap:{height:50,borderWidth:1,borderRadius:14,marginBottom:10,flexDirection:'row',alignItems:'center'},passwordInput:{flex:1,height:'100%',paddingHorizontal:14,fontSize:13},eyeButton:{width:48,height:'100%',alignItems:'center',justifyContent:'center'},button:{height:50,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:6},buttonText:{color:'#fff',fontWeight:'900'},error:{color:'#b24f64',fontSize:10,marginBottom:5},links:{marginTop:16,gap:10,alignItems:'center'},link:{fontSize:10,fontWeight:'900'}});
