import { ScrollView, View, Text, StyleSheet, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { ArrowLeft, Bell, Shield, Palette } from 'lucide-react-native';
import { Card } from '../src/components/UI';
import { useTheme } from '../src/context/ThemeContext';

export default function Settings(){const {theme,palettes,id,setTheme}=useTheme();return <SafeAreaView style={[s.safe,{backgroundColor:theme.bg}]}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.back()} style={[s.back,{backgroundColor:theme.surface,borderColor:theme.line}]}><ArrowLeft color={theme.text} size={19}/></Pressable><Text style={[s.title,{color:theme.text}]}>Settings</Text></View><Text style={[s.section,{color:theme.text}]}>Appearance</Text><View style={s.themeGrid}>{Object.values(palettes).map(p=><Pressable key={p.id} onPress={()=>setTheme(p.id)} style={[s.theme,{backgroundColor:p.surface,borderColor:id===p.id?theme.primary:p.line,borderWidth:id===p.id?2:1}]}><View style={[s.swatch,{backgroundColor:p.primary}]}/><View><Text style={{color:p.text,fontSize:11,fontWeight:'900'}}>{p.name}</Text><Text style={{color:p.muted,fontSize:8,marginTop:2}}>Tap to apply</Text></View></Pressable>)}</View><Text style={[s.section,{color:theme.text}]}>Preferences</Text><Card style={s.row}><Bell color={theme.primary} size={19}/><View style={s.grow}><Text style={[s.rowTitle,{color:theme.text}]}>Notifications</Text><Text style={[s.rowSub,{color:theme.muted}]}>UI ready; live notification settings come later.</Text></View></Card><Card style={s.row}><Shield color={theme.primary} size={19}/><View style={s.grow}><Text style={[s.rowTitle,{color:theme.text}]}>Account & security</Text><Text style={[s.rowSub,{color:theme.muted}]}>Existing Firebase remains untouched during UI testing.</Text></View></Card><Card style={s.row}><Palette color={theme.primary} size={19}/><View style={s.grow}><Text style={[s.rowTitle,{color:theme.text}]}>Comfort-first colors</Text><Text style={[s.rowSub,{color:theme.muted}]}>All four palettes now use softer surfaces and contrast.</Text></View></Card></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},content:{padding:18,paddingBottom:34},top:{flexDirection:'row',alignItems:'center',gap:12,marginTop:5,marginBottom:22},back:{width:42,height:42,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},title:{fontSize:27,fontWeight:'900',letterSpacing:-.8},section:{fontSize:14,fontWeight:'900',marginVertical:13},themeGrid:{flexDirection:'row',flexWrap:'wrap',gap:9},theme:{width:'48%',borderRadius:17,padding:13,flexDirection:'row',alignItems:'center',gap:10},swatch:{width:30,height:30,borderRadius:10},row:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:9},grow:{flex:1},rowTitle:{fontSize:12,fontWeight:'900'},rowSub:{fontSize:9,lineHeight:14,marginTop:3}});
