import { View, Text, Pressable, StyleSheet } from 'react-native';
import { BookOpen, Sparkles } from 'lucide-react-native';
import { useTheme } from '../context/ThemeContext';

export function Brand({compact=false}){const {theme}=useTheme();return <View style={s.brand}><View style={[s.mark,{backgroundColor:theme.primary}]}><BookOpen color="#fff" size={compact?18:21}/><Sparkles color="#fff" size={9} style={s.spark}/></View>{!compact&&<View><Text style={[s.brandTitle,{color:theme.text}]}>EQUALLEARN</Text><Text style={[s.brandSub,{color:theme.muted}]}>Learn. Understand. Create equality.</Text></View>}</View>}
export function Card({children,style}){const {theme}=useTheme();return <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line},style]}>{children}</View>}
export function Progress({value}){const {theme}=useTheme();return <View style={[s.track,{backgroundColor:theme.surface2}]}><View style={[s.fill,{backgroundColor:theme.primary,width:`${Math.max(0,Math.min(100,value))}%`}]} /></View>}
export function Pill({children}){const {theme}=useTheme();return <View style={[s.pill,{backgroundColor:theme.soft}]}><Text style={[s.pillText,{color:theme.primary}]}>{children}</Text></View>}
export function PrimaryButton({children,onPress}){const {theme}=useTheme();return <Pressable onPress={onPress} style={({pressed})=>[s.button,{backgroundColor:theme.primary,opacity:pressed?0.82:1}]}><Text style={s.buttonText}>{children}</Text></Pressable>}
const s=StyleSheet.create({brand:{flexDirection:'row',alignItems:'center',gap:10},mark:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},spark:{position:'absolute',right:5,top:5},brandTitle:{fontSize:14,fontWeight:'900',letterSpacing:.7},brandSub:{fontSize:8,marginTop:3},card:{borderWidth:1,borderRadius:20,padding:17},track:{height:7,borderRadius:20,overflow:'hidden'},fill:{height:'100%',borderRadius:20},pill:{alignSelf:'flex-start',borderRadius:100,paddingHorizontal:8,paddingVertical:5},pillText:{fontSize:9,fontWeight:'800',textTransform:'uppercase'},button:{height:48,borderRadius:14,alignItems:'center',justifyContent:'center'},buttonText:{color:'#fff',fontWeight:'800',fontSize:13}});
