import { Alert, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { BarChart3, BookOpen, GraduationCap, Layers3, Pencil, Plus, RefreshCw, Trash2, Users } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import RoleTopBar from '../components/RoleTopBar';
import { ActionButton, ChoiceRow, EmptyState, ErrorState, Header, Input, LoadingState, Notice, Panel, pct, ProfileBlock, Row, Screen, SearchInput, SectionTitle, Sheet, StatCard } from '../components/FunctionalUI';
import { ProfilePhotoUploader } from '../components/AppwriteUploaders';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { useLoad } from '../hooks/useLoad';
import { activateAssignment, assignTeacher, createTeacherAccount, deactivateAssignment, deleteAssignment, deleteStudentProfile, deleteTeacherProfile, formatWhen, generateClassGroupsFromStudents, getAssignments, getClassGroups, getLessons, getModules, getProgress, getQuestions, getUsers, lower, normalizeSection, normalizeYearLevel, reportRows, retrieveAssignment, saveProfile, studentCourse, studentSection, timestampMs, updateTeacher, YEAR_LEVELS } from '../lib/data';

async function adminBundle(){const[users,modules,lessons,questions,progress,assignments,classGroups]=await Promise.all([getUsers(),getModules(),getLessons(),getQuestions(),getProgress(),getAssignments(),getClassGroups()]);return{users,modules,lessons,questions,progress,assignments,classGroups};}

export function AdminHome(){
  const load=useLoad(adminBundle,[]);
  if(load.loading)return <LoadingState/>;
  if(load.error)return <ErrorState message={load.error} onRetry={load.refresh}/>;
  const {users,modules,lessons,progress,assignments}=load.data;
  const students=users.filter(x=>lower(x.role)==='student'),teachers=users.filter(x=>lower(x.role)==='teacher');
  const avg=progress.length?Math.round(progress.reduce((s,p)=>s+Number(p.percentage||0),0)/progress.length):0;
  const recent=[...progress].sort((a,b)=>timestampMs(b.completedAt)-timestampMs(a.completedAt)).slice(0,6);
  return <Screen><RoleTopBar profilePath="/admin/profile"/><Header eyebrow="Administration" title="EqualLearn control center" text="Live system oversight using the existing Firebase data."/><StatCard label="Students" value={students.length} detail={`${students.filter(x=>lower(x.status||'active')!=='inactive').length} active`} Icon={Users}/><StatCard label="Teachers" value={teachers.length} detail={`${assignments.filter(x=>lower(x.status||'active')==='active').length} active designations`} Icon={GraduationCap}/><StatCard label="Modules / lessons" value={`${modules.length} / ${lessons.length}`} Icon={BookOpen}/><StatCard label="Average score" value={pct(avg)} detail={`${progress.length} assessment records`} Icon={BarChart3}/><SectionTitle title="Latest results"/><Panel>{recent.map(p=>{const student=students.find(x=>x.id===p.userId),lesson=lessons.find(x=>x.id===p.lessonId);return <Row key={p.id} title={student?.fullname||'Student'} subtitle={`${lesson?.title||'Lesson'} · ${pct(p.percentage)}`} meta={formatWhen(p.completedAt)}/>;})}{!recent.length?<EmptyState title="No assessment activity yet"/>:null}</Panel></Screen>;
}

export function AdminStudents(){
  const load=useLoad(adminBundle,[]);
  const[search,setSearch]=useState(''),[year,setYear]=useState('all'),[selected,setSelected]=useState(null),[message,setMessage]=useState('');
  if(load.loading)return <LoadingState/>;
  const students=(load.data?.users||[]).filter(x=>lower(x.role)==='student'),progress=load.data?.progress||[],lessons=load.data?.lessons||[];
  let rows=students.filter(x=>!search||`${x.fullname} ${x.studentNumber} ${x.email} ${studentSection(x)}`.toLowerCase().includes(search.toLowerCase()));
  if(year!=='all')rows=rows.filter(x=>normalizeYearLevel(x.yearLevel)===year);
  const stats=student=>{const p=progress.filter(x=>x.userId===student.id),avg=p.length?Math.round(p.reduce((a,x)=>a+Number(x.percentage||0),0)/p.length):0;return{p,avg,passed:p.filter(x=>x.result==='passing').length};};
  function remove(student){Alert.alert('Delete student',`Delete ${student.fullname||student.email} from EqualLearn? This removes the Firestore profile, progress, and notifications. The Firebase Authentication credential remains until privileged server-side deletion is configured.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await deleteStudentProfile(student.id);setSelected(null);setMessage('Student profile and learning records deleted.');load.refresh();}catch(e){setMessage(e.message);}}}]);}
  return <Screen><Header eyebrow="Students" title="Registered learners" text="Search student profiles and review learning records."/><SearchInput value={search} onChangeText={setSearch} placeholder="Search name, ID, email, section…"/><ChoiceRow value={year} onChange={setYear} options={[{value:'all',label:'All years'},...YEAR_LEVELS.map(x=>({value:x,label:x}))]}/><Notice>{message}</Notice><Panel>{rows.map(student=>{const x=stats(student);return <Row key={student.id} title={student.fullname||student.email} subtitle={`${studentCourse(student)} · ${normalizeYearLevel(student.yearLevel)||'—'} · Section ${studentSection(student)||'—'}`} meta={`${x.p.length} attempts · ${pct(x.avg)} average`} onPress={()=>setSelected(student)}/>;})}{!rows.length?<EmptyState title="No students match this view"/>:null}</Panel><Sheet visible={!!selected} title="Student profile" onClose={()=>setSelected(null)} tall>{selected?<><ProfileBlock person={selected} role="student"/><SectionTitle title="Learning history"/>{stats(selected).p.map(p=><Row key={p.id} title={lessons.find(l=>l.id===p.lessonId)?.title||'Lesson'} subtitle={`${p.score}/${p.total} · ${pct(p.percentage)} · ${p.result}`} meta={formatWhen(p.completedAt)}/>)}{!stats(selected).p.length?<EmptyState title="No quiz history"/>:null}<ActionButton variant="danger" onPress={()=>remove(selected)}>Delete student profile</ActionButton></>:null}</Sheet></Screen>;
}

export function AdminTeachers(){
  const load=useLoad(adminBundle,[]);
  const[search,setSearch]=useState(''),[edit,setEdit]=useState(null),[selected,setSelected]=useState(null),[message,setMessage]=useState('');
  if(load.loading)return <LoadingState/>;
  const teachers=(load.data?.users||[]).filter(x=>lower(x.role)==='teacher');
  const rows=teachers.filter(x=>!search||`${x.fullname} ${x.email} ${x.department}`.toLowerCase().includes(search.toLowerCase()));
  const open=t=>{setEdit({id:t?.id||'',fullname:t?.fullname||'',email:t?.email||'',password:'',department:t?.department||'',phone:t?.phone||'',bio:t?.bio||'',status:t?.status||'active'});setMessage('');};
  async function save(){try{if(!edit.fullname.trim()||!edit.email.trim())throw new Error('Full name and email are required.');if(edit.id){await updateTeacher(edit.id,{fullname:edit.fullname.trim(),department:edit.department.trim(),phone:edit.phone.trim(),bio:edit.bio.trim(),status:edit.status});}else{if(edit.password.length<6)throw new Error('Temporary password must contain at least 6 characters.');await createTeacherAccount(edit);}setEdit(null);load.refresh();}catch(e){setMessage(e.message||'Unable to save teacher.');}}
  function remove(teacher){Alert.alert('Delete teacher',`Delete ${teacher.fullname||teacher.email}'s Firestore profile? Their Firebase Authentication credential remains until server-side deletion is configured.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await deleteTeacherProfile(teacher.id);setSelected(null);load.refresh();}}]);}
  return <Screen><Header eyebrow="Teachers" title="Teacher accounts" text="Create and maintain teacher profiles." right={<Pressable onPress={()=>open()}><Plus size={24}/></Pressable>}/><SearchInput value={search} onChangeText={setSearch} placeholder="Search teachers…"/><Panel>{rows.map(t=><Row key={t.id} title={t.fullname||t.email} subtitle={t.email} meta={`${t.department||'No department'} · ${t.status||'active'}`} onPress={()=>setSelected(t)}/>)}{!rows.length?<EmptyState title="No teachers found"/>:null}</Panel><Sheet visible={!!selected} title="Teacher profile" onClose={()=>setSelected(null)} tall>{selected?<><ProfileBlock person={selected} role="teacher"/><View style={s.two}><ActionButton style={{flex:1}} onPress={()=>{open(selected);setSelected(null);}}>Edit</ActionButton><ActionButton style={{flex:1}} variant="danger" onPress={()=>remove(selected)}>Delete profile</ActionButton></View></>:null}</Sheet><Sheet visible={!!edit} title={`${edit?.id?'Edit':'Create'} teacher`} onClose={()=>setEdit(null)} tall><Input label="Full name" value={edit?.fullname||''} onChangeText={v=>setEdit(x=>({...x,fullname:v}))}/><Input label="Email" value={edit?.email||''} onChangeText={v=>setEdit(x=>({...x,email:v}))} editable={!edit?.id} keyboardType="email-address" autoCapitalize="none"/>{!edit?.id?<Input label="Temporary password" value={edit?.password||''} onChangeText={v=>setEdit(x=>({...x,password:v}))} secureTextEntry/>:null}<Input label="Department" value={edit?.department||''} onChangeText={v=>setEdit(x=>({...x,department:v}))}/><Input label="Phone" value={edit?.phone||''} onChangeText={v=>setEdit(x=>({...x,phone:v}))} keyboardType="phone-pad"/><Input label="Bio" value={edit?.bio||''} onChangeText={v=>setEdit(x=>({...x,bio:v}))} multiline/><Label>Status</Label><ChoiceRow value={edit?.status||'active'} onChange={v=>setEdit(x=>({...x,status:v}))} options={['active','inactive']}/><Notice type="error">{message}</Notice><ActionButton onPress={save}>Save teacher</ActionButton></Sheet></Screen>;
}

export function AdminSections(){
  const load=useLoad(adminBundle,[]);
  const[form,setForm]=useState({classGroupId:'',yearLevel:'',teacherId:''}),[message,setMessage]=useState('');
  if(load.loading)return <LoadingState/>;
  const{classGroups,assignments,users}=load.data||{classGroups:[],assignments:[],users:[]};
  const teachers=users.filter(x=>lower(x.role)==='teacher'&&lower(x.status||'active')!=='inactive');
  const group=classGroups.find(x=>x.id===form.classGroupId);
  const years=group?.yearLevels?.length?group.yearLevels.map(normalizeYearLevel).filter(y=>YEAR_LEVELS.includes(y)):YEAR_LEVELS;
  const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  async function refreshSections(){try{const count=await generateClassGroupsFromStudents();setMessage(`${count} sections generated/refreshed.`);load.refresh();}catch(e){setMessage(e.message);}}
  async function assign(){try{if(!form.classGroupId||!form.yearLevel||!form.teacherId)throw new Error('Choose a section, year, and teacher.');await assignTeacher(form);setMessage('Teacher designation saved and activated.');load.refresh();}catch(e){setMessage(e.message);}}
  function deactivate(id){Alert.alert('Deactivate designation','Students will stop using this teacher designation until you activate it again.',[{text:'Cancel',style:'cancel'},{text:'Deactivate',onPress:async()=>{try{await deactivateAssignment(id);setMessage('Teacher designation deactivated.');load.refresh();}catch(e){setMessage(e.message);}}}]);}
  function remove(id){Alert.alert('Delete designation','Move this designation to the recoverable deleted state? You can retrieve it later.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await deleteAssignment(id);setMessage('Teacher designation moved to deleted.');load.refresh();}catch(e){setMessage(e.message);}}}]);}
  async function activate(id){try{await activateAssignment(id);setMessage('Teacher designation activated.');load.refresh();}catch(e){setMessage(e.message);}}
  async function retrieve(id){try{await retrieveAssignment(id);setMessage('Teacher designation retrieved as inactive. Activate it when ready.');load.refresh();}catch(e){setMessage(e.message);}}
  return <Screen><Header eyebrow="Teacher Designation" title="Teacher Designations" text="Assign teachers to sections and manage active, inactive, or recoverable deleted designations." right={<Pressable onPress={refreshSections}><RefreshCw size={22}/></Pressable>}/><Notice>{message}</Notice><Panel><Label>Section</Label><Selection rows={classGroups} selected={form.classGroupId} label={x=>`Section ${x.section||'—'} · ${x.studentCount||0} students`} onChange={id=>{set('classGroupId',id);set('yearLevel','');}}/><Label>Year Level</Label><ChoiceRow value={form.yearLevel} onChange={v=>set('yearLevel',v)} options={years}/><Label>Teacher</Label><Selection rows={teachers} selected={form.teacherId} label={x=>x.fullname||x.email} onChange={id=>set('teacherId',id)}/><ActionButton onPress={assign}>Save designation</ActionButton></Panel><SectionTitle title="Student sections"/><Panel>{classGroups.map(g=><Row key={g.id} title={`Section ${g.section||'—'}`} subtitle={`${g.course||'BSIT'} · ${(g.yearLevels||[]).map(normalizeYearLevel).filter(Boolean).join(', ')||'—'}`} meta={`${g.studentCount||0} students`}/>)}{!classGroups.length?<EmptyState title="No sections yet"/>:null}</Panel><SectionTitle label="Designation records" title="Teacher Designations"/><View style={s.designationList}>{assignments.map(a=>{const status=lower(a.status||'active');return <Panel key={a.id} style={s.designationCard}><Row title={`${a.course||'BSIT'} · ${normalizeYearLevel(a.yearLevel)||'—'} · Section ${normalizeSection(a.section||a.cohort)||'—'}`} subtitle={a.teacherName||'—'} meta={`Status: ${status}`}/>{status==='deleted'?<ActionButton variant="secondary" onPress={()=>retrieve(a.id)}>Retrieve designation</ActionButton>:<View style={s.designationActions}>{status==='inactive'?<ActionButton style={s.designationAction} onPress={()=>activate(a.id)}>Activate</ActionButton>:<ActionButton style={s.designationAction} variant="secondary" onPress={()=>deactivate(a.id)}>Deactivate</ActionButton>}<ActionButton style={s.designationAction} variant="danger" onPress={()=>remove(a.id)}>Delete</ActionButton></View>}</Panel>})}{!assignments.length?<Panel><EmptyState title="No teacher designations yet"/></Panel>:null}</View></Screen>;
}

export function AdminReports(){
  const load=useLoad(adminBundle,[]);
  const[search,setSearch]=useState(''),[year,setYear]=useState('all'),[result,setResult]=useState('all'),[status,setStatus]=useState('all');
  if(load.loading)return <LoadingState/>;
  let rows=reportRows(load.data.users,load.data.progress);
  if(search)rows=rows.filter(x=>`${x.fullname} ${x.studentNumber} ${x.email} ${studentSection(x)}`.toLowerCase().includes(search.toLowerCase()));
  if(year!=='all')rows=rows.filter(x=>normalizeYearLevel(x.yearLevel)===year);
  if(result!=='all')rows=rows.filter(x=>x.result===result);
  if(status!=='all')rows=rows.filter(x=>lower(x.schoolStatus)===status);
  const avg=rows.length?Math.round(rows.reduce((s,x)=>s+x.grade,0)/rows.length):0,passing=rows.filter(x=>x.result==='passing').length;
  async function shareCsv(){const h=['Full name','Student ID','Email','Course','Year Level','Section','Grade','Result','Status'];const all=[h,...rows.map(x=>[x.fullname,x.studentNumber,x.email,studentCourse(x),normalizeYearLevel(x.yearLevel),studentSection(x),x.grade,x.result,x.schoolStatus])];const csv=all.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');await Share.share({title:'EqualLearn student reports',message:csv});}
  return <Screen><Header eyebrow="Reports" title="Student performance" text="Grades are calculated from saved quiz percentages."/><StatCard label="Students shown" value={rows.length} Icon={Users}/><StatCard label="Passing" value={passing} Icon={GraduationCap}/><StatCard label="Average" value={pct(avg)} Icon={BarChart3}/><SearchInput value={search} onChangeText={setSearch} placeholder="Search students…"/><ChoiceRow value={year} onChange={setYear} options={[{value:'all',label:'All years'},...YEAR_LEVELS.map(x=>({value:x,label:x}))]}/><ChoiceRow value={result} onChange={setResult} options={[{value:'all',label:'All results'},{value:'passing',label:'Passing'},{value:'failing',label:'Failing'}]}/><ChoiceRow value={status} onChange={setStatus} options={[{value:'all',label:'All statuses'},{value:'active',label:'Active'},{value:'inactive',label:'Inactive'}]}/><ActionButton variant="secondary" onPress={shareCsv}>Share CSV report</ActionButton><SectionTitle title="Report records"/><Panel>{rows.map(x=><Row key={x.id} title={x.fullname||x.email} subtitle={`${studentCourse(x)} · ${normalizeYearLevel(x.yearLevel)||'—'} · Section ${studentSection(x)||'—'}`} meta={`${pct(x.grade)} · ${x.result} · ${x.schoolStatus}`}/>)}{!rows.length?<EmptyState title="No report records match these filters"/>:null}</Panel></Screen>;
}

export function AdminProfile(){
  const{firebaseUser,profile,refreshProfile,logout}=useAuth();
  const[form,setForm]=useState({fullname:profile?.fullname||'',phone:profile?.phone||'',bio:profile?.bio||''}),[message,setMessage]=useState('');
  const preview=useMemo(()=>({...profile,...form}),[profile,form]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  async function save(){if(!form.fullname.trim()){setMessage('Enter your full name.');return;}await saveProfile(firebaseUser.uid,{fullname:form.fullname.trim(),phone:form.phone.trim(),bio:form.bio.trim()});await refreshProfile();setMessage('Profile updated successfully.');}
  const leave=()=>Alert.alert('Logout','Are you sure you want to logout?',[{text:'Cancel',style:'cancel'},{text:'Logout',style:'destructive',onPress:async()=>{await logout();router.replace('/login');}}]);
  return <Screen><Header eyebrow="Profile" title="Admin profile" text="Manage your EqualLearn administrator information."/><ProfileBlock person={preview} role="admin"/><ProfilePhotoUploader/><SectionTitle title="Edit profile"/><Panel><Input label="Full name" value={form.fullname} onChangeText={v=>set('fullname',v)}/><Input label="Email" value={profile?.email||''} editable={false}/><Input label="Phone" value={form.phone} onChangeText={v=>set('phone',v)} keyboardType="phone-pad"/><Input label="Bio" value={form.bio} onChangeText={v=>set('bio',v)} multiline/><Notice type={message.includes('success')?'success':'error'}>{message}</Notice><ActionButton onPress={save}>Save profile</ActionButton></Panel><View style={{height:10}}/><ActionButton variant="secondary" onPress={()=>router.push('/settings')}>Settings</ActionButton><View style={{height:8}}/><ActionButton variant="secondary" onPress={()=>router.push('/about')}>About EqualLearn</ActionButton><View style={{height:8}}/><ActionButton variant="danger" onPress={leave}>Logout</ActionButton></Screen>;
}

function Label({children}){const{theme}=useTheme();return <Text style={[s.label,{color:theme.text}]}>{children}</Text>}
function Selection({rows,selected,label,onChange}){const{theme}=useTheme();return <View style={s.selection}>{rows.map(row=><Pressable key={row.id} onPress={()=>onChange(row.id)} style={[s.selectItem,{borderColor:selected===row.id?theme.primary:theme.line,backgroundColor:selected===row.id?theme.soft:theme.surface}]}><Text numberOfLines={2} style={{color:theme.text,fontSize:10,fontWeight:'800'}}>{label(row)}</Text></Pressable>)}</View>;}
const s=StyleSheet.create({two:{flexDirection:'row',gap:8,marginTop:14},label:{fontSize:10,fontWeight:'800',marginBottom:7},selection:{gap:7,marginBottom:12},selectItem:{borderWidth:1,borderRadius:12,padding:11},designationList:{gap:10},designationCard:{gap:10},designationActions:{flexDirection:'row',gap:8},designationAction:{flex:1}});
